package tech.doit.app.school_manager.domain.model.enums

enum class ProfileType(private val description: String) {
    ADMIN("ADMIN"),
    PROFESSOR("PROFESSOR"),
    SCHOOL_PRINCIPAL("SCHOOL_PRINCIPAL"),
    SCHOOL_GROUP_ADMINISTRATOR("SCHOOL_GROUP_ADMINISTRATOR"),
    CONCIERGE("CONCIERGE"),
    SECURITY("SECURITY"),
    RECEPTIONIST("RECEPTIONIST"),
    PEDAGOGICAL_COORDINATOR("PEDAGOGICAL_COORDINATOR"),
    ACTIVITY_COORDINATOR("ACTIVITY_COORDINATOR"),
    SECRETARY("SECRETARY"),
    STUDENT("STUDENT");

    fun getDescription(): String = description
}
